runtime: go
api_version: go1

handlers:

  # All URLs are handled by the Go application script
  - url: /.*
    script: _go_app

nobuild_files:
  #  - src/gopkg.in
  #  - src/golang.org
  #  - src/github.com
  - vendor